### ISSUE TITLE
BUG: AttributeError: 'Namespace' object has no attribute 'verbosity'

### ISSUE THREAD

**Issue by uschi2000** [kraken-build/kraken-core#5]
```
❯ krakenw q
[krakenw] reusing build environment of type VENV
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/rfink/git/kraken-hs/build/.kraken/venv/lib/python3.9/site-packages/kraken/cli/main.py", line 375, in <module>
    main()
  File "/Users/rfink/git/kraken-hs/build/.kraken/venv/lib/python3.9/site-packages/kraken/cli/main.py", line 371, in main
    main_internal(prog, argv)
  File "/Users/rfink/git/kraken-hs/build/.kraken/venv/lib/python3.9/site-packages/kraken/cli/main.py", line 317, in main_internal
    LoggingOptions.collect(args).init_logging()
  File "/Users/rfink/git/kraken-hs/build/.kraken/venv/lib/python3.9/site-packages/kraken/cli/option_sets.py", line 42, in collect
    verbosity=args.verbosity,
AttributeError: 'Namespace' object has no attribute 'verbosity'
```

**Comment by uschi2000** [comment]
(Don't know how to find out the kraken-core version used. I tried `krakenw --version`, but that gives me the wrapper version only (0.1.12))

**Comment by tetigi** [comment]
Hey @uschi2000 - this seems to be a bug in the wrapper, where it is not correctly delegating to the underlying `kraken` arg-parse implementation. This means that the normally helpful error message is just replaced with rubbish (which is bad).

I believe the `kraken-core` version will be whatever is in your lock file - `krakenw` is just the wrapper that invokes whatever version is specified there.

You can still install a specific version of kraken-cli and use that for exploring the API a bit, if you're getting stuck, and we'll get this fixed in the meantime! If you have the correct command, `krakenw` should still work as expected (eg. `krakenw q ls` will function normally).

**Comment by NiklasRosenstein** [comment]
Thank you for reporting the issue. It's actually been an issue in `kraken-core` where the argument parser for `kraken q` does not get a `--verbosity` option. This is because it doesn't combine well with the same option on subcommands.

**Comment by uschi2000** [comment]
Thanks both!
